# netlify.toml

[build]
  # This tells Netlify where your serverless functions are.
  functions = "netlify/functions"

# This rule redirects all API requests to your function.
[[redirects]]
  from = "/server/*"
  to = "/.netlify/functions/api/:splat"
  status = 200